# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "cargo" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo" # See documentation for possible values
    directory: "/color/" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo" # See documentation for possible values
    directory: "/common/" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo" # See documentation for possible values
    directory: "/dice/" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo" # See documentation for possible values
    directory: "/disadvantage/" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo" # See documentation for possible values
    directory: "/zauber/" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo" # See documentation for possible values
    directory: "/decay_series/" # Location of package manifests
    schedule:
      interval: "daily"
