[package]
name = "zerfallsreihen"
authors = ["Rafael Sundorf"]
version = "1.0.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.130", features = ["derive"] }
serde_yaml = "0.8.21"
common = { version = "1.0.0", path = "../common" }
macros = { version = "1.0.0", path = "../macros" }
ansi_term = "0.12.1"