name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build_linux_arm7:
    name: Linux ARMv7
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: armv7-unknown-linux-gnueabihf
          override: true
      - uses: actions-rs/cargo@v1
        name: Build Release
        with:
          use-cross: true
          command: build
          args: --target armv7-unknown-linux-gnueabihf --release --all-features
      - uses: actions-rs/cargo@v1
        name: Build Debug
        with:
          use-cross: true
          command: build
          args: --target armv7-unknown-linux-gnueabihf --all-features
      - name: Copy binaries
        run: |
          mv target/armv7-unknown-linux-gnueabihf/release/würfeln ./wuerfeln
          mv target/armv7-unknown-linux-gnueabihf/debug/würfeln ./wuerfeln-debug
      - uses: actions/upload-artifact@v2
        with:
          name: wuerfeln-armv7-unknown-linux-gnueabihf
          path: |
            wuerfeln
            wuerfeln-debug
  build_linux_x86:
    name: Linux x86_64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-gnu
          override: true
      - uses: actions-rs/cargo@v1
        name: Build Release
        with:
          use-cross: true
          command: build
          args: --target x86_64-unknown-linux-gnu --release --all-features
      - uses: actions-rs/cargo@v1
        name: Build Debug
        with:
          use-cross: true
          command: build
          args: --target x86_64-unknown-linux-gnu --all-features
      - name: Rust Cargo Deb Package Build (amd64, Debian)
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source $HOME/.cargo/env
          cargo install --version 1.33.0 cargo-deb
          cargo deb --target=x86_64-unknown-linux-gnu
      - name: Copy binaries
        run: |
          mv target/x86_64-unknown-linux-gnu/release/würfeln ./wuerfeln
          mv target/x86_64-unknown-linux-gnu/debug/würfeln ./wuerfeln-debug
          mv target/x86_64-unknown-linux-gnu/debian/*.deb ./
      - uses: actions/upload-artifact@v2
        with:
          name: wuerfeln-x86_64-unknown-linux-gnu
          path: |
            wuerfeln
            wuerfeln-debug
            *.deb
  build_windows_x86:
    name: Windows
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-pc-windows-gnu
          override: true
      - uses: actions-rs/cargo@v1
        name: Build Release
        with:
          use-cross: true
          command: build
          args: --target x86_64-pc-windows-gnu --release --all-features
      - uses: actions-rs/cargo@v1
        name: Build Debug
        with:
          use-cross: true
          command: build
          args: --target x86_64-pc-windows-gnu --all-features
      - name: Copy binaries
        run: |
          mv target/x86_64-pc-windows-gnu/release/würfeln.exe ./wuerfeln.exe
          mv target/x86_64-pc-windows-gnu/debug/würfeln.exe ./debug-wuerfeln.exe
      - uses: actions/upload-artifact@v2
        with:
          name: wuerfeln-x86_64-pc-windows-gnu
          path: |
            wuerfeln.exe
            debug-wuerfeln.exe
  build_android_aarch64:
    name: Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: aarch64-linux-android
          override: true
      - uses: actions-rs/cargo@v1
        name: Build Release
        with:
          use-cross: true
          command: build
          args: --target aarch64-linux-android --release --all-features
      - uses: actions-rs/cargo@v1
        name: Build Debug
        with:
          use-cross: true
          command: build
          args: --target aarch64-linux-android --all-features
      - name: Copy binaries
        run: |
          mv target/aarch64-linux-android/release/wuerfeln ./
          mv target/aarch64-linux-android/debug/würfeln ./debug-wuerfeln
      - uses: actions/upload-artifact@v2
        with:
          name: wuerfeln-aarch64-linux-android
          path: |
            wuerfeln
            debug-wuerfeln
