# This is a basic workflow to help you get started with Actions
name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_linux_arm7:
    name: Linux ARMv7
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: armv7-unknown-linux-gnueabihf
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target armv7-unknown-linux-gnueabihf --release --all-features
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target armv7-unknown-linux-gnueabihf --all-features
      - name: Rust Cargo Deb Package Build (armv7, Debian)
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
          cargo install cargo-deb
          cargo deb --target=armv7-unknown-linux-gnueabihf
      - name: Copy binaries
        run: |
          mv target/armv7-unknown-linux-gnueabihf/release/würfeln ./
          mv target/armv7-unknown-linux-gnueabihf/debug/würfeln ./debug-würfeln
          mv target/armv7-unknown-linux-gnueabihf/debug/würfeln/debian/*.deb ./
      - uses: actions/upload-artifact@v2
        with:
          name: wuerfeln-armv7-unknown-linux-gnueabihf
          path: |
            würfeln
            debug-würfeln
            *.deb
  build_linux_x86:
    name: Linux x86_64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-gnu
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target x86_64-unknown-linux-gnu --release --all-features
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target x86_64-unknown-linux-gnu --all-features
      - name: Rust Cargo Deb Package Build (amd64, Debian)
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
          cargo install cargo-deb
          cargo deb --target=x86_64-unknown-linux-gnu
      - name: Copy binaries
        run: |
          mv target/x86_64-unknown-linux-gnu/release/würfeln ./
          mv target/x86_64-unknown-linux-gnu/debug/würfeln ./debug-würfeln
          mv target/x86_64-unknown-linux-gnu/debian/*.deb ./
      - uses: actions/upload-artifact@v2
        with:
          name: wuerfeln-x86_64-unknown-linux-gnu
          path: |
            würfeln
            debug-würfeln
            *.deb
  build_windows_x86:
    name: Windows
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-pc-windows-gnu
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target x86_64-pc-windows-gnu --release --all-features
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target x86_64-pc-windows-gnu --all-features
      - name: Copy binaries
        run: |
          mv target/x86_64-pc-windows-gnu/release/würfeln.exe ./
          mv target/x86_64-pc-windows-gnu/debug/würfeln.exe ./würfeln-debug.exe
      - uses: actions/upload-artifact@v2
        with:
          name: wuerfeln-x86_64-pc-windows-gnu
          path: |
            würfeln.exe
            würfeln-debug.exe
  build_android_aarch64:
    name: Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: aarch64-linux-android
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target aarch64-linux-android --release --all-features
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target aarch64-linux-android --all-features
      - name: Copy binaries
        run: |
          mv target/aarch64-linux-android/release/würfeln ./
          mv target/aarch64-linux-android/debug/würfeln ./würfeln-debug
      - uses: actions/upload-artifact@v2
        with:
          name: wuerfeln-aarch64-linux-android
          path: |
            würfeln
            würfeln-debug
